"""empty message

Revision ID: 704d1d513f75
Revises: 
Create Date: 2022-07-28 13:07:12.741103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704d1d513f75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', 'value'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', 'value'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('callsign', sa.String(length=120), nullable=True),
    sa.Column('hull', sa.Integer(), nullable=True),
    sa.Column('agility', sa.Integer(), nullable=True),
    sa.Column('systems', sa.Integer(), nullable=True),
    sa.Column('engineering', sa.Integer(), nullable=True),
    sa.Column('manna', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('gear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['gear_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_tree',
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['location.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['location.id'], )
    )
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_job', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.DateTime(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gm_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['mission_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_state_changes',
    sa.Column('current_state', sa.Integer(), nullable=True),
    sa.Column('next_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_state'], ['mission_state.id'], ),
    sa.ForeignKeyConstraint(['next_state'], ['mission_state.id'], )
    )
    op.create_table('user_to_pilot',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('mission_to_loot',
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('gear_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gear_id'], ['gear.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], )
    )
    op.create_table('pilot_to_mission',
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], )
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('is_refunded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['gear.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('pilot_to_mission')
    op.drop_table('mission_to_loot')
    op.drop_table('user_to_pilot')
    op.drop_table('mission_state_changes')
    op.drop_table('mission')
    op.drop_table('location_tree')
    op.drop_table('gear')
    op.drop_table('user')
    op.drop_table('pilot')
    op.drop_table('mission_state')
    op.drop_table('location')
    op.drop_table('gear_type')
    # ### end Alembic commands ###
