"""empty message

Revision ID: 738fee8348e0
Revises: cff022d2262a
Create Date: 2022-07-26 19:09:13.386050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738fee8348e0'
down_revision = 'cff022d2262a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('gm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mission', 'user', ['gm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mission', type_='foreignkey')
    op.drop_column('mission', 'gm_id')
    # ### end Alembic commands ###
