"""empty message

Revision ID: cff022d2262a
Revises: e1cd994d4429
Create Date: 2022-07-26 18:53:47.808445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff022d2262a'
down_revision = 'e1cd994d4429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_tree',
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['location.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['location.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_tree')
    # ### end Alembic commands ###
