"""empty message

Revision ID: e1cd994d4429
Revises: 696630b2e661
Create Date: 2022-07-26 17:12:24.507045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cd994d4429'
down_revision = '696630b2e661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mission_state', ['value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mission_state', type_='unique')
    # ### end Alembic commands ###
